# Generated by Django 3.0.7 on 2020-06-23 19:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Place for title')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Place for date')),
                ('link', models.SlugField(max_length=160, unique=True, verbose_name='Place for link')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('text', models.TextField(max_length=5000, verbose_name='Comment')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Place for date')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Article', verbose_name='Article')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Review', verbose_name='Parent')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.Author'),
        ),
    ]
