# Generated by Django 3.0.7 on 2020-06-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='upvotes',
            field=models.PositiveSmallIntegerField(default=0, max_length=1000, verbose_name='amount of upvotes'),
        ),
    ]
