# Generated by Django 3.0.7 on 2020-06-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='upvotes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='amount of upvotes'),
        ),
    ]
